### ISSUE TITLE
Evaluator crashes when there is no test report

### ISSUE THREAD

**Issue by fonglh** [Coursemology/evaluator-slave#61]
```
bundler: failed to load command: bin/evaluator (bin/evaluator)
NoMethodError: undefined method `force_encoding' for nil:NilClass
```

Result of #60.

The `rescue` block doesn't kick in first if the evaluation gets killed.

**Comment by allenwq** [comment]
It not supposed to be rescued, from the code rescue only works for `Docker::Error::NotFoundError`
